<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260916213016 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, version INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FA7AEFFB5E237E06 ON attribute (name)');
        $this->addSql('CREATE TABLE attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, sort_order INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78672EEAB6E62EFA ON attribute_option (attribute_id)');
        $this->addSql('CREATE TABLE cv (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, user_id INT NOT NULL, position_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B66FFE92A76ED395 ON cv (user_id)');
        $this->addSql('CREATE INDEX IDX_B66FFE92DD842E46 ON cv (position_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_position ON cv (user_id, position_id)');
        $this->addSql('CREATE TABLE cv_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cv_id INT NOT NULL, recruiter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD2DA06FCFE419E2 ON cv_like (cv_id)');
        $this->addSql('CREATE INDEX IDX_CD2DA06F156BE243 ON cv_like (recruiter_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_recruiter ON cv_like (cv_id, recruiter_id)');
        $this->addSql('CREATE TABLE discussion_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, position_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FE4C0BBDD842E46 ON discussion_post (position_id)');
        $this->addSql('CREATE INDEX IDX_7FE4C0BBF675F31B ON discussion_post (author_id)');
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, is_public BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, max_projects INT DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_462CE4F5B03A8386 ON position (created_by_id)');
        $this->addSql('CREATE TABLE position_tag_link (position_id INT NOT NULL, project_tag_id INT NOT NULL, PRIMARY KEY (position_id, project_tag_id))');
        $this->addSql('CREATE INDEX IDX_FC8474F0DD842E46 ON position_tag_link (position_id)');
        $this->addSql('CREATE INDEX IDX_FC8474F0AD76885B ON position_tag_link (project_tag_id)');
        $this->addSql('CREATE TABLE position_access_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operator VARCHAR(20) NOT NULL, value VARCHAR(255) DEFAULT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D97A8C6DD842E46 ON position_access_rule (position_id)');
        $this->addSql('CREATE INDEX IDX_5D97A8C6B6E62EFA ON position_access_rule (attribute_id)');
        $this->addSql('CREATE TABLE position_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sort_order INT NOT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF5BEE86DD842E46 ON position_attribute (position_id)');
        $this->addSql('CREATE INDEX IDX_AF5BEE86B6E62EFA ON position_attribute (attribute_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_attribute ON position_attribute (position_id, attribute_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, period_start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description TEXT DEFAULT NULL, version INT DEFAULT 1 NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEA76ED395 ON project (user_id)');
        $this->addSql('CREATE TABLE project_tag_link (project_id INT NOT NULL, project_tag_id INT NOT NULL, PRIMARY KEY (project_id, project_tag_id))');
        $this->addSql('CREATE INDEX IDX_E5EDAD9C166D1F9C ON project_tag_link (project_id)');
        $this->addSql('CREATE INDEX IDX_E5EDAD9CAD76885B ON project_tag_link (project_tag_id)');
        $this->addSql('CREATE TABLE project_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_91F26D605E237E06 ON project_tag (name)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, location VARCHAR(255) DEFAULT NULL, photo_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EC93D70DA76ED395 ON user_attribute_value (user_id)');
        $this->addSql('CREATE INDEX IDX_EC93D70DB6E62EFA ON user_attribute_value (attribute_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_attribute ON user_attribute_value (user_id, attribute_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT FK_78672EEAB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_B66FFE92A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_B66FFE92DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CD2DA06FCFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CD2DA06F156BE243 FOREIGN KEY (recruiter_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_7FE4C0BBDD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_7FE4C0BBF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_tag_link ADD CONSTRAINT FK_FC8474F0DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_tag_link ADD CONSTRAINT FK_FC8474F0AD76885B FOREIGN KEY (project_tag_id) REFERENCES project_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_tag_link ADD CONSTRAINT FK_E5EDAD9C166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_tag_link ADD CONSTRAINT FK_E5EDAD9CAD76885B FOREIGN KEY (project_tag_id) REFERENCES project_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_attribute_value ADD CONSTRAINT FK_EC93D70DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_attribute_value ADD CONSTRAINT FK_EC93D70DB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute_option DROP CONSTRAINT FK_78672EEAB6E62EFA');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE92A76ED395');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE92DD842E46');
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CD2DA06FCFE419E2');
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CD2DA06F156BE243');
        $this->addSql('ALTER TABLE discussion_post DROP CONSTRAINT FK_7FE4C0BBDD842E46');
        $this->addSql('ALTER TABLE discussion_post DROP CONSTRAINT FK_7FE4C0BBF675F31B');
        $this->addSql('ALTER TABLE position DROP CONSTRAINT FK_462CE4F5B03A8386');
        $this->addSql('ALTER TABLE position_tag_link DROP CONSTRAINT FK_FC8474F0DD842E46');
        $this->addSql('ALTER TABLE position_tag_link DROP CONSTRAINT FK_FC8474F0AD76885B');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6DD842E46');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6B6E62EFA');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86DD842E46');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86B6E62EFA');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEA76ED395');
        $this->addSql('ALTER TABLE project_tag_link DROP CONSTRAINT FK_E5EDAD9C166D1F9C');
        $this->addSql('ALTER TABLE project_tag_link DROP CONSTRAINT FK_E5EDAD9CAD76885B');
        $this->addSql('ALTER TABLE user_attribute_value DROP CONSTRAINT FK_EC93D70DA76ED395');
        $this->addSql('ALTER TABLE user_attribute_value DROP CONSTRAINT FK_EC93D70DB6E62EFA');
        $this->addSql('DROP TABLE attribute');
        $this->addSql('DROP TABLE attribute_option');
        $this->addSql('DROP TABLE cv');
        $this->addSql('DROP TABLE cv_like');
        $this->addSql('DROP TABLE discussion_post');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE position_tag_link');
        $this->addSql('DROP TABLE position_access_rule');
        $this->addSql('DROP TABLE position_attribute');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_tag_link');
        $this->addSql('DROP TABLE project_tag');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_attribute_value');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
